# Generated by Django 4.1.7 on 2023-05-06 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='composition',
        ),
        migrations.RemoveField(
            model_name='product',
            name='prodapp',
        ),
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('IP', 'indoorplant'), ('OP', 'outdoorplant'), ('RP', 'rareplant'), ('SP', 'succulents'), ('VP', 'variegatedplant'), ('CP', 'cactus')], max_length=2),
        ),
        migrations.AlterField(
            model_name='product',
            name='description',
            field=models.TextField(),
        ),
    ]
