# Generated by Django 4.1.7 on 2023-07-15 09:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_slider_delete_slide'),
    ]

    operations = [
        migrations.RenameField(
            model_name='slider',
            old_name='description',
            new_name='details',
        ),
        migrations.AlterField(
            model_name='slider',
            name='image',
            field=models.ImageField(upload_to='slider_images'),
        ),
    ]
