# Generated by Django 4.1.7 on 2023-12-07 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_reviewrating_delete_review'),
    ]

    operations = [
        migrations.AddField(
            model_name='reviewrating',
            name='ip',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='reviewrating',
            name='subject',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
